# Generated by Django 5.1.7 on 2025-04-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='playoff.tournament'),
            preserve_default=False,
        ),
    ]
